name: CI FOR MVP

on:
  push:
    branches:
      - develop

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Setup MySQL
#        uses: mirromutth/mysql-action@v1.1
#        with:
#          mysql database: 'kkijuk'
#          mysql user: 'test'
#          mysql password: 'testPW'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Get short SHA
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Generate application.properties
        run: |
          echo commit.hash=${{ steps.slug.outputs.sha7 }} >> ./src/main/resources/application-prod.properties
#          echo ${{ secrets.DATASOURCE_DB_URL }} >> ./src/main/resources/application-prod.properties
#          echo ${{ secrets.DATASOURCE_DB_USERNAME }} >> ./src/main/resources/application-prod.properties
#          echo ${{ secrets.DATASOURCE_DB_PASSWORD }} >> ./src/main/resources/application.properties

#          touch ./src/main/resources/application.properties
#          touch ./src/test/resources/application.properties
#          echo ${{ secrets.PROPERTIES }} >> ./src/main/resources/application.properties
#          echo ${{ secrets.PROPERTIES }} >> ./src/test/resources/application.properties
#
#          echo ${{ secrets.DB_PROPERTIES }} >> ./src/main/resources/application.properties
#          echo ${{ secrets.TEST_DB_PROPERTIES }} >> ./src/test/resources/application.properties


      - name: Build with Gradle Wrapper
        run: ./gradlew build
